-- MySQL Script generated by MySQL Workbench
-- Sat Sep 11 14:48:14 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gourmet
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gourmet` ;

-- -----------------------------------------------------
-- Schema gourmet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gourmet` DEFAULT CHARACTER SET utf8 ;
USE `gourmet` ;

-- -----------------------------------------------------
-- Table `gourmet`.`plates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gourmet`.`plates` ;

CREATE TABLE IF NOT EXISTS `gourmet`.`plates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `describe` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gourmet`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gourmet`.`categories` ;

CREATE TABLE IF NOT EXISTS `gourmet`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gourmet`.`categories_plates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gourmet`.`categories_plates` ;

CREATE TABLE IF NOT EXISTS `gourmet`.`categories_plates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `category_id` INT NOT NULL,
  `plate_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pivot_plates_categories_categories1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_pivot_plates_categories_plates1_idx` (`plate_id` ASC) VISIBLE,
  CONSTRAINT `fk_pivot_plates_categories_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `gourmet`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pivot_plates_categories_plates1`
    FOREIGN KEY (`plate_id`)
    REFERENCES `gourmet`.`plates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `gourmet`.`plates`
-- -----------------------------------------------------
START TRANSACTION;
USE `gourmet`;
INSERT INTO `gourmet`.`plates` (`id`, `name`, `created_at`, `updated_at`, `describe`) VALUES (1, 'Bolo de Chocolate', '2021-09-11 14:25:00', '2021-09-11 14:26:00', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `gourmet`.`categories`
-- -----------------------------------------------------
START TRANSACTION;
USE `gourmet`;
INSERT INTO `gourmet`.`categories` (`id`, `name`, `created_at`, `updated_at`) VALUES (1, 'Massa', '2021-09-11 14:21:00', '2021-09-11 14:21:00');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gourmet`.`categories_plates`
-- -----------------------------------------------------
START TRANSACTION;
USE `gourmet`;
INSERT INTO `gourmet`.`categories_plates` (`id`, `created_at`, `updated_at`, `category_id`, `plate_id`) VALUES (1, '2021-09-11 14:30:00', '2021-09-11 14:30:00', 1, 1);

COMMIT;

